// generated by newgenasym  Thu Dec 14 23:05:11 2017


module adp5053 (\0 , \1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 ,
        \25 , \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \39 , \4 , \40 ,
        \41 , \42 , \43 , \44 , \45 , \46 , \47 , \48 , \5 , \6 , \7 , \8 , \9 );
    output \0 ;
    input \1 ;
    input \10 ;
    input \11 ;
    input \12 ;
    input \13 ;
    input \14 ;
    input \15 ;
    input \16 ;
    input \17 ;
    output \18 ;
    output \19 ;
    input \2 ;
    input \20 ;
    input \21 ;
    input \22 ;
    input \23 ;
    input \24 ;
    input \25 ;
    input \26 ;
    input \27 ;
    input \28 ;
    input \29 ;
    input \3 ;
    input \30 ;
    input \31 ;
    input \32 ;
    input \33 ;
    input \34 ;
    input \35 ;
    input \36 ;
    input \37 ;
    input \38 ;
    input \39 ;
    input \4 ;
    input \40 ;
    output \41 ;
    input \42 ;
    output \43 ;
    input \44 ;
    input \45 ;
    input \46 ;
    input \47 ;
    input \48 ;
    input \5 ;
    output \6 ;
    input \7 ;
    output \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
