// generated by newgenasym  Fri Dec 15 12:11:11 2017


module adp5053 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 , \25 ,
        \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \39 , \4 , \40 , \41 ,
        \42 , \43 , \44 , \45 , \46 , \47 , \48 , \49 , \5 , \6 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    input \12 ;
    input \13 ;
    input \14 ;
    output \15 ;
    input \16 ;
    input \17 ;
    input \18 ;
    input \19 ;
    input \2 ;
    output \20 ;
    input \21 ;
    output \22 ;
    input \23 ;
    input \24 ;
    input \25 ;
    output \26 ;
    output \27 ;
    input \28 ;
    inout \29 ;
    output \3 ;
    input \30 ;
    inout \31 ;
    input \32 ;
    output \33 ;
    output \34 ;
    input \35 ;
    input \36 ;
    input \37 ;
    inout \38 ;
    output \39 ;
    input \4 ;
    input \40 ;
    inout \41 ;
    input \42 ;
    inout \43 ;
    input \44 ;
    input \45 ;
    output \46 ;
    inout \47 ;
    input \48 ;
    input \49 ;
    input \5 ;
    inout \6 ;
    input \7 ;
    output \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
