-- generated by newgenasym Sat Jan 13 21:42:02 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \pesd0402-140\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \pesd0402-140\;
