-- generated by newgenasym Wed May 09 16:49:58 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end diode;
