// generated by newgenasym  Mon Mar 05 16:39:57 2018


module \rj45-ge-magnetics  (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 , m1, m2);
    inout \1 ;
    inout \10 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout m1;
    inout m2;


    initial
        begin
        end

endmodule
