-- generated by newgenasym Wed May 09 11:42:44 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_s is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_s;
