-- generated by newgenasym Wed Dec 15 16:03:59 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head1x2_s is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end head1x2_s;
