// generated by newgenasym  Thu Nov 11 14:15:24 2010


module head2x3 (a1, a2, a3, b1, b2, b3);
    inout a1;
    inout a2;
    inout a3;
    inout b1;
    inout b2;
    inout b3;


    initial
        begin
        end

endmodule
