-- generated by newgenasym Fri Feb 17 10:02:35 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        OUT    STD_LOGIC);
end crystal;
