-- generated by newgenasym Thu May 17 16:25:36 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end l;
