-- generated by newgenasym Tue May 15 13:56:32 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end l;
