-- generated by newgenasym Wed Aug 13 17:49:16 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end l;
