-- generated by newgenasym Mon Apr 09 17:03:17 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esd is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end esd;
