// generated by newgenasym  Wed May 09 14:04:52 2018


module \osc-4  (gnd, nnc, out, vdd);
    input gnd;
    input nnc;
    output out;
    input vdd;


    initial
        begin
        end

endmodule
