-- generated by newgenasym Wed May 09 14:04:52 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \osc-4\ is
    port (    
	GND:       IN     STD_LOGIC;    
	NNC:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end \osc-4\;
