-- generated by newgenasym Mon Jan 15 19:36:35 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \osc-12mhz\ is
    port (    
	GND:       INOUT  STD_LOGIC;    
	NNC:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end \osc-12mhz\;
