// generated by newgenasym  Fri Dec 11 11:35:57 2009


module \cy7c68013a-128axc  (a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8,
        a9, agnd_1, agnd_2, avcc_1, avcc_2, bkpt, clkout, \cs* ,
        \ctl0/flaga , \ctl1/flagb , \ctl2/flagc , ctl3, ctl4, ctl5, d0, d1,
        d2, d3, d4, d5, d6, d7, dminus, dplus, ea, gnd_1, gnd_2, gnd_3,
        gnd_4, gnd_5, gnd_6, gnd_7, gnd_8, gnd_9, ifclk, int4, \int5* ,
        nc_1, nc_2, nc_3, \oe* , \pa0/int0* , \pa1/int1* , \pa2/sloe ,
        \pa3/wu2 , \pa4/fifoadr0 , \pa5/fifoadr1 , \pa6/pktend ,
        \pa7/flagd/slcs* , \pb0/fd0 , \pb1/fd1 , \pb2/fd2 , \pb3/fd3 ,
        \pb4/fd4 , \pb5/fd5 , \pb6/fd6 , \pb7/fd7 , \pc0/gpifadr0 ,
        \pc1/gpifadr1 , \pc2/gpifadr2 , \pc3/gpifadr3 , \pc4/gpifadr4 ,
        \pc5/gpifadr5 , \pc6/gpifadr6 , \pc7/gpifadr7 , \pd0/fd8 ,
        \pd1/fd9 , \pd2/fd10 , \pd3/fd11 , \pd4/fd12 , \pd5/fd13 , \pd6/fd14 ,
        \pd7/fd15 , \pe0/t0out , \pe1/t1out , \pe2/t2out , \pe3/rxd0out ,
        \pe4/rxd1out , \pe5/int6 , \pe6/t2ex , \pe7/gpifadr8 , \psen* , \rd* ,
        \rdy0/slrd , \rdy1/slwr , rdy2, rdy3, rdy4, rdy5, reserved,
        \reset* , rxd0, rxd1, scl, sda, t0, t1, t2, txd0, txd1, vcc_1,
        vcc_2, vcc_3, vcc_4, vcc_5, vcc_6, vcc_7, vcc_8, vcc_9,
        wakeup, \wr* , xtalin, xtalout);
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout agnd_1;
    inout agnd_2;
    inout avcc_1;
    inout avcc_2;
    inout bkpt;
    inout clkout;
    inout \cs* ;
    inout \ctl0/flaga ;
    inout \ctl1/flagb ;
    inout \ctl2/flagc ;
    inout ctl3;
    inout ctl4;
    inout ctl5;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout dminus;
    inout dplus;
    inout ea;
    inout gnd_1;
    inout gnd_2;
    inout gnd_3;
    inout gnd_4;
    inout gnd_5;
    inout gnd_6;
    inout gnd_7;
    inout gnd_8;
    inout gnd_9;
    inout ifclk;
    inout int4;
    inout \int5* ;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout \oe* ;
    inout \pa0/int0* ;
    inout \pa1/int1* ;
    inout \pa2/sloe ;
    inout \pa3/wu2 ;
    inout \pa4/fifoadr0 ;
    inout \pa5/fifoadr1 ;
    inout \pa6/pktend ;
    inout \pa7/flagd/slcs* ;
    inout \pb0/fd0 ;
    inout \pb1/fd1 ;
    inout \pb2/fd2 ;
    inout \pb3/fd3 ;
    inout \pb4/fd4 ;
    inout \pb5/fd5 ;
    inout \pb6/fd6 ;
    inout \pb7/fd7 ;
    inout \pc0/gpifadr0 ;
    inout \pc1/gpifadr1 ;
    inout \pc2/gpifadr2 ;
    inout \pc3/gpifadr3 ;
    inout \pc4/gpifadr4 ;
    inout \pc5/gpifadr5 ;
    inout \pc6/gpifadr6 ;
    inout \pc7/gpifadr7 ;
    inout \pd0/fd8 ;
    inout \pd1/fd9 ;
    inout \pd2/fd10 ;
    inout \pd3/fd11 ;
    inout \pd4/fd12 ;
    inout \pd5/fd13 ;
    inout \pd6/fd14 ;
    inout \pd7/fd15 ;
    inout \pe0/t0out ;
    inout \pe1/t1out ;
    inout \pe2/t2out ;
    inout \pe3/rxd0out ;
    inout \pe4/rxd1out ;
    inout \pe5/int6 ;
    inout \pe6/t2ex ;
    inout \pe7/gpifadr8 ;
    inout \psen* ;
    inout \rd* ;
    inout \rdy0/slrd ;
    inout \rdy1/slwr ;
    inout rdy2;
    inout rdy3;
    inout rdy4;
    inout rdy5;
    inout reserved;
    inout \reset* ;
    inout rxd0;
    inout rxd1;
    inout scl;
    inout sda;
    inout t0;
    inout t1;
    inout t2;
    inout txd0;
    inout txd1;
    inout vcc_1;
    inout vcc_2;
    inout vcc_3;
    inout vcc_4;
    inout vcc_5;
    inout vcc_6;
    inout vcc_7;
    inout vcc_8;
    inout vcc_9;
    inout wakeup;
    inout \wr* ;
    inout xtalin;
    inout xtalout;


    initial
        begin
        end

endmodule
