-- generated by newgenasym Mon Dec 13 15:36:47 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity npn is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end npn;
