// generated by newgenasym  Wed May 16 16:29:30 2018


module gl850g (agnd1, agnd2, agnd3, agnd4, avdd1, avdd2, avdd3, avdd4,
        avdd5, dm0, dm1, dm2, dm3, dm4, dp0, dp1, dp2, dp3, dp4, dvdd1,
        dvdd2, \dvdd3/sel27 , \dvdd4/sel48 , \ovcur1# , \ovcur2# , \ovcur3# ,
        \ovcur4# , pamber1, pamber2, pamber3, pamber4, pgang, pgreen1,
        pgreen2, pgreen3, pgreen4, pself, \pwren1# , \pwren2# , \pwren3# ,
        \pwren4# , \reset# , rref, test, v33, v5, x1, x2);
    inout agnd1;
    inout agnd2;
    inout agnd3;
    inout agnd4;
    inout avdd1;
    inout avdd2;
    inout avdd3;
    inout avdd4;
    inout avdd5;
    inout dm0;
    inout dm1;
    inout dm2;
    inout dm3;
    inout dm4;
    inout dp0;
    inout dp1;
    inout dp2;
    inout dp3;
    inout dp4;
    inout dvdd1;
    inout dvdd2;
    inout \dvdd3/sel27 ;
    inout \dvdd4/sel48 ;
    inout \ovcur1# ;
    inout \ovcur2# ;
    inout \ovcur3# ;
    inout \ovcur4# ;
    inout pamber1;
    inout pamber2;
    inout pamber3;
    inout pamber4;
    inout pgang;
    inout pgreen1;
    inout pgreen2;
    inout pgreen3;
    inout pgreen4;
    inout pself;
    inout \pwren1# ;
    inout \pwren2# ;
    inout \pwren3# ;
    inout \pwren4# ;
    inout \reset# ;
    inout rref;
    inout test;
    inout v33;
    inout v5;
    inout x1;
    inout x2;


    initial
        begin
        end

endmodule
