// generated by newgenasym  Wed Feb 07 19:55:08 2007


module usb3300 (clkout, cpen, data, dir, dm, dp, extvbus, gnd, id, nxt, pad,
        rbias, reg_en, reset, stp, vbus, \vdd1.8 , \vdd3.3 , \vdda1.8 , xi,
        xo);
    output clkout;
    output cpen;
    inout [7:0] data;
    output dir;
    inout dm;
    inout dp;
    input extvbus;
    input [2:1] gnd;
    input id;
    output nxt;
    input pad;
    input rbias;
    inout reg_en;
    input reset;
    input stp;
    inout vbus;
    input [2:1] \vdd1.8 ;
    input [4:1] \vdd3.3 ;
    input \vdda1.8 ;
    input xi;
    output xo;


    initial
        begin
        end

endmodule
