-- generated by newgenasym Thu Nov 25 14:59:23 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_s is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_s;
