-- generated by newgenasym Fri Jan 16 11:29:05 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_s is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_s;
