// generated by newgenasym  Wed May 16 16:36:42 2018


module lm3526 (\ena* , \enb* , flaga, flagb, gnd, in, outa, outb);
    input \ena* ;
    input \enb* ;
    input flaga;
    input flagb;
    input gnd;
    input in;
    output outa;
    output outb;


    initial
        begin
        end

endmodule
