// generated by newgenasym  Thu Jan 08 15:17:16 2009


module lm3526 (\ena* , \enb* , flaga, flagb, gnd, in, outa, outb);
    input \ena* ;
    input \enb* ;
    input flaga;
    input flagb;
    input gnd;
    input in;
    output outa;
    output outb;


    initial
        begin
        end

endmodule
