-- generated by newgenasym Sun May 06 14:44:40 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm3526 is
    port (    
	\ena*\:    IN     STD_LOGIC;    
	\enb*\:    IN     STD_LOGIC;    
	FLAGA:     IN     STD_LOGIC;    
	FLAGB:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	OUTA:      OUT    STD_LOGIC;    
	OUTB:      OUT    STD_LOGIC);
end lm3526;
