// generated by newgenasym  Wed May 09 14:04:42 2018


module \osc-12mhz  (gnd, nnc, out, vdd);
    inout gnd;
    inout nnc;
    inout out;
    inout vdd;


    initial
        begin
        end

endmodule
