// generated by newgenasym  Mon Jan 15 19:36:35 2018


module \osc-12mhz  (gnd, nnc, out, vdd);
    inout gnd;
    inout nnc;
    inout out;
    inout vdd;


    initial
        begin
        end

endmodule
