// generated by newgenasym  Tue May 15 15:52:26 2018


module \osc-12mhz  (gnd, nnc, out, vdd);
    inout gnd;
    inout nnc;
    inout out;
    inout vdd;


    initial
        begin
        end

endmodule
