-- generated by newgenasym Wed May 09 14:04:42 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \osc-12mhz\ is
    port (    
	GND:       INOUT  STD_LOGIC;    
	NNC:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end \osc-12mhz\;
