-- generated by newgenasym Sun May 20 09:32:28 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity usb3300 is
    port (    
	CLKOUT:    OUT    STD_LOGIC;    
	CPEN:      OUT    STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	DIR:       OUT    STD_LOGIC;    
	DM:        INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	EXTVBUS:   IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC_VECTOR (2 DOWNTO 1);    
	ID:        IN     STD_LOGIC;    
	NXT:       OUT    STD_LOGIC;    
	PAD:       IN     STD_LOGIC;    
	RBIAS:     IN     STD_LOGIC;    
	REG_EN:    INOUT  STD_LOGIC;    
	RESET:     IN     STD_LOGIC;    
	STP:       IN     STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC;    
	\vdd1.8\:  IN     STD_LOGIC_VECTOR (2 DOWNTO 1);    
	\vdd3.3\:  IN     STD_LOGIC_VECTOR (4 DOWNTO 1);    
	\vdda1.8\: IN     STD_LOGIC;    
	XI:        IN     STD_LOGIC;    
	XO:        OUT    STD_LOGIC);
end usb3300;
