// generated by newgenasym  Sat Dec 27 13:02:23 2008


module at24c02 (a1, a2, a3, gnd, nc, scl, sda, vcc);
    input a1;
    input a2;
    input a3;
    input gnd;
    inout nc;
    input scl;
    inout sda;
    input vcc;


    initial
        begin
        end

endmodule
