-- generated by newgenasym Sat Dec 27 13:02:23 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity at24c02 is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end at24c02;
