// generated by newgenasym  Mon Apr 23 22:21:24 2018


module adv7511kstz (avdd, avdd_2, avdd_3, bgvdd, cec, cec_clk, clk, d0, d1, d10,
        d11, d12, d13, d14, d15, d16, d17, d18, d19, d2, d20, d21, d22,
        d23, d24, d25, d26, d27, d28, d29, d3, d30, d31, d32, d33, d34,
        d35, d4, d5, d6, d7, d8, d9, ddcscl, ddcsda, de, dsd0, dsd1, dsd2,
        dsd3, dsd4, dsd5, dsd_clk, dvdd, dvdd_2, dvdd_3, dvdd_4,
        dvdd_5, gnd, gnd_10, gnd_11, gnd_2, gnd_3, gnd_4, gnd_5,
        gnd_6, gnd_7, gnd_8, gnd_9, \heac+ , \heac- , hpd, hsync, int,
        iso0, iso1, iso2, iso3, lrclk, mclk, mvdd, pd, plvdd, pvdd,
        pvdd_2, r_ext, scl, sclk, sda, spdif, spdif_out, sync, \tx0+ ,
        \tx0- , \tx1+ , \tx1- , \tx2+ , \tx2- , \txc+ , \txc- );
    inout avdd;
    inout avdd_2;
    inout avdd_3;
    inout bgvdd;
    inout cec;
    inout cec_clk;
    inout clk;
    inout d0;
    inout d1;
    inout d10;
    inout d11;
    inout d12;
    inout d13;
    inout d14;
    inout d15;
    inout d16;
    inout d17;
    inout d18;
    inout d19;
    inout d2;
    inout d20;
    inout d21;
    inout d22;
    inout d23;
    inout d24;
    inout d25;
    inout d26;
    inout d27;
    inout d28;
    inout d29;
    inout d3;
    inout d30;
    inout d31;
    inout d32;
    inout d33;
    inout d34;
    inout d35;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout d8;
    inout d9;
    inout ddcscl;
    inout ddcsda;
    inout de;
    inout dsd0;
    inout dsd1;
    inout dsd2;
    inout dsd3;
    inout dsd4;
    inout dsd5;
    inout dsd_clk;
    inout dvdd;
    inout dvdd_2;
    inout dvdd_3;
    inout dvdd_4;
    inout dvdd_5;
    inout gnd;
    inout gnd_10;
    inout gnd_11;
    inout gnd_2;
    inout gnd_3;
    inout gnd_4;
    inout gnd_5;
    inout gnd_6;
    inout gnd_7;
    inout gnd_8;
    inout gnd_9;
    inout \heac+ ;
    inout \heac- ;
    inout hpd;
    inout hsync;
    inout int;
    inout iso0;
    inout iso1;
    inout iso2;
    inout iso3;
    inout lrclk;
    inout mclk;
    inout mvdd;
    inout pd;
    inout plvdd;
    inout pvdd;
    inout pvdd_2;
    inout r_ext;
    inout scl;
    inout sclk;
    inout sda;
    inout spdif;
    inout spdif_out;
    inout sync;
    inout \tx0+ ;
    inout \tx0- ;
    inout \tx1+ ;
    inout \tx1- ;
    inout \tx2+ ;
    inout \tx2- ;
    inout \txc+ ;
    inout \txc- ;


    initial
        begin
        end

endmodule
