-- generated by newgenasym Wed Mar 14 16:21:43 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end r;
