-- generated by newgenasym Wed May 09 15:14:43 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x7 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (13 DOWNTO 0));
end head2x7;
