// generated by newgenasym  Tue May 16 21:02:41 2006


module adp3338 (gnd, in, out, out_t);
    inout gnd;
    inout in;
    inout out;
    inout out_t;


    initial
        begin
        end

endmodule
