// generated by newgenasym  Tue Dec 26 16:39:52 2017


module spx1117adj (adj, in, out, out_t);
    inout adj;
    inout in;
    inout out;
    inout out_t;


    initial
        begin
        end

endmodule
