-- generated by newgenasym Fri Oct 29 19:01:56 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mbrd835l is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end mbrd835l;
