-- generated by newgenasym Wed May 09 17:17:54 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \osc-125m-dif\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end \osc-125m-dif\;
