// generated by newgenasym  Fri Feb 17 10:00:24 2017


module \osc-4  (gnd, nnc, out, vdd);
    input gnd;
    input nnc;
    output out;
    input vdd;


    initial
        begin
        end

endmodule
