// generated by newgenasym  Tue Feb 06 10:19:51 2018


module \osc-4  (gnd, nnc, out, vdd);
    input gnd;
    input nnc;
    output out;
    input vdd;


    initial
        begin
        end

endmodule
