-- generated by newgenasym Fri Feb 17 10:00:24 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \osc-4\ is
    port (    
	GND:       IN     STD_LOGIC;    
	NNC:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end \osc-4\;
