-- generated by newgenasym Mon Jan 22 16:59:29 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpd4s012 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end tpd4s012;
