-- generated by newgenasym Wed Dec 08 13:21:06 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end diode;
