-- generated by newgenasym Fri Jul 05 11:56:29 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity npn8050 is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end npn8050;
