-- generated by newgenasym Tue May 15 10:27:51 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lb is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end lb;
