-- generated by newgenasym Wed May 09 15:46:39 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        OUT    STD_LOGIC);
end crystal;
