-- generated by newgenasym Tue Feb 28 09:49:30 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sensor_pad is
    port (    
	\1\:       INOUT  STD_LOGIC);
end sensor_pad;
