-- generated by newgenasym Fri Sep 25 11:01:09 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity m25p40 is
    port (    
	C:         IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	\hold*\:   IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\s*\:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC;    
	\w*\:      IN     STD_LOGIC);
end m25p40;
