-- generated by newgenasym Tue Dec 21 14:07:44 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c;
