-- generated by newgenasym Tue Jan 02 21:57:53 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bss123lt1 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end bss123lt1;
