// generated by newgenasym  Thu Aug 07 13:20:43 2014


module \7m_serial  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
