// generated by newgenasym  Tue May 15 15:56:12 2018


module ncp1529 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
