// generated by newgenasym  Mon May 07 11:29:14 2018


module ncp1529 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
