-- generated by newgenasym Tue May 15 15:56:12 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ncp1529 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end ncp1529;
