-- generated by newgenasym Mon Dec 13 15:49:01 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lb is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end lb;
