// generated by newgenasym  Tue May 15 10:14:23 2018


module fds9926a (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;


    initial
        begin
        end

endmodule
