-- generated by newgenasym Tue May 16 21:02:41 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adp3338 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	OUT_T:     INOUT  STD_LOGIC);
end adp3338;
