// generated by newgenasym  Mon Mar 05 11:15:54 2018


module \mtfc8gacaaam-1m  (a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9, b1,
        b10, b11, b12, b13, b14, b2, b3, b4, b5, b6, b7, b8, b9, c1, c10,
        c11, c12, c13, c14, c2, c3, c4, c5, c6, c7, c8, c9, d1, d12, d13,
        d14, d2, d3, d4, e1, e10, e12, e13, e14, e2, e3, e5, e6, e7, e8, e9,
        f1, f10, f12, f13, f14, f2, f3, f5, g1, g10, g12, g13, g14, g2, g3,
        g5, h1, h10, h12, h13, h14, h2, h3, h5, j1, j10, j12, j13, j14, j2,
        j3, j5, k1, k10, k12, k13, k14, k2, k3, k5, k6, k7, k8, k9, l1, l12,
        l13, l14, l2, l3, m1, m10, m11, m12, m13, m14, m2, m3, m4, m5, m6,
        m7, m8, m9, n1, n10, n11, n12, n13, n14, n2, n3, n4, n5, n6, n7, n8,
        n9, p1, p10, p11, p12, p13, p14, p2, p3, p4, p5, p6, p7, p8, p9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b13;
    inout b14;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    inout c1;
    inout c10;
    inout c11;
    inout c12;
    inout c13;
    inout c14;
    inout c2;
    inout c3;
    inout c4;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    inout c9;
    inout d1;
    inout d12;
    inout d13;
    inout d14;
    inout d2;
    inout d3;
    inout d4;
    inout e1;
    inout e10;
    inout e12;
    inout e13;
    inout e14;
    inout e2;
    inout e3;
    inout e5;
    inout e6;
    inout e7;
    inout e8;
    inout e9;
    inout f1;
    inout f10;
    inout f12;
    inout f13;
    inout f14;
    inout f2;
    inout f3;
    inout f5;
    inout g1;
    inout g10;
    inout g12;
    inout g13;
    inout g14;
    inout g2;
    inout g3;
    inout g5;
    inout h1;
    inout h10;
    inout h12;
    inout h13;
    inout h14;
    inout h2;
    inout h3;
    inout h5;
    inout j1;
    inout j10;
    inout j12;
    inout j13;
    inout j14;
    inout j2;
    inout j3;
    inout j5;
    inout k1;
    inout k10;
    inout k12;
    inout k13;
    inout k14;
    inout k2;
    inout k3;
    inout k5;
    inout k6;
    inout k7;
    inout k8;
    inout k9;
    inout l1;
    inout l12;
    inout l13;
    inout l14;
    inout l2;
    inout l3;
    inout m1;
    inout m10;
    inout m11;
    inout m12;
    inout m13;
    inout m14;
    inout m2;
    inout m3;
    inout m4;
    inout m5;
    inout m6;
    inout m7;
    inout m8;
    inout m9;
    inout n1;
    inout n10;
    inout n11;
    inout n12;
    inout n13;
    inout n14;
    inout n2;
    inout n3;
    inout n4;
    inout n5;
    inout n6;
    inout n7;
    inout n8;
    inout n9;
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p13;
    inout p14;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
