// generated by newgenasym  Tue May 08 17:36:26 2018


module adv7612bswz (ap0, \ap1/i2s_tdm , ap2, ap3, ap4, ap5, cec, cs, cvdd, cvdd_2,
        cvdd_3, ddca_scl, ddca_sda, ddcb_scl, ddcb_sda, de, dvdd,
        dvdd_2, dvdd_3, dvdd_4, dvddio, dvddio_2, dvddio_3,
        dvddio_4, ep, \hpa_a/int2 , hpa_b, hs, int1, llc, \mclk/int2 , nc,
        nc_2, p0, p1, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p2,
        p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p3, p30, p31,
        p32, p33, p34, p35, p4, p5, p6, p7, p8, p9, pvdd, reset, \rxa_0+ ,
        \rxa_0- , \rxa_1+ , \rxa_1- , \rxa_2+ , \rxa_2- , rxa_5v, \rxa_c+ ,
        \rxa_c- , \rxb_0+ , \rxb_0- , \rxb_1+ , \rxb_1- , \rxb_2+ , \rxb_2- ,
        rxb_5v, \rxb_c+ , \rxb_c- , scl, \sclk/int2 , sda, tvdd, tvdd_2,
        tvdd_3, tvdd_4, tvdd_5, tvdd_6, \vs/field/alsb , xtaln, xtalp);
    inout ap0;
    inout \ap1/i2s_tdm ;
    inout ap2;
    inout ap3;
    inout ap4;
    inout ap5;
    inout cec;
    input cs;
    input cvdd;
    input cvdd_2;
    input cvdd_3;
    inout ddca_scl;
    input ddca_sda;
    input ddcb_scl;
    input ddcb_sda;
    inout de;
    input dvdd;
    input dvdd_2;
    input dvdd_3;
    input dvdd_4;
    input dvddio;
    input dvddio_2;
    input dvddio_3;
    input dvddio_4;
    input ep;
    inout \hpa_a/int2 ;
    inout hpa_b;
    output hs;
    inout int1;
    output llc;
    inout \mclk/int2 ;
    inout nc;
    inout nc_2;
    output p0;
    output p1;
    output p10;
    output p11;
    output p12;
    output p13;
    output p14;
    output p15;
    output p16;
    output p17;
    output p18;
    output p19;
    output p2;
    output p20;
    output p21;
    output p22;
    output p23;
    output p24;
    output p25;
    output p26;
    output p27;
    output p28;
    output p29;
    output p3;
    output p30;
    output p31;
    output p32;
    output p33;
    output p34;
    output p35;
    output p4;
    output p5;
    output p6;
    output p7;
    output p8;
    output p9;
    input pvdd;
    inout reset;
    input \rxa_0+ ;
    input \rxa_0- ;
    input \rxa_1+ ;
    input \rxa_1- ;
    input \rxa_2+ ;
    input \rxa_2- ;
    input rxa_5v;
    input \rxa_c+ ;
    input \rxa_c- ;
    input \rxb_0+ ;
    input \rxb_0- ;
    input \rxb_1+ ;
    input \rxb_1- ;
    input \rxb_2+ ;
    input \rxb_2- ;
    input rxb_5v;
    input \rxb_c+ ;
    input \rxb_c- ;
    inout scl;
    inout \sclk/int2 ;
    inout sda;
    input tvdd;
    input tvdd_2;
    input tvdd_3;
    input tvdd_4;
    input tvdd_5;
    input tvdd_6;
    output \vs/field/alsb ;
    inout xtaln;
    inout xtalp;


    initial
        begin
        end

endmodule
