// generated by newgenasym  Tue May 15 14:46:47 2018


module \wiper-sw  (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
