-- generated by newgenasym Tue Mar 20 16:12:22 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \wiper-sw\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end \wiper-sw\;
