// generated by newgenasym  Fri Sep 25 11:01:09 2009


module m25p40 (c, d, \hold* , q, \s* , vcc, vss, \w* );
    input c;
    input d;
    input \hold* ;
    output q;
    input \s* ;
    input vcc;
    input vss;
    input \w* ;


    initial
        begin
        end

endmodule
