// generated by newgenasym  Wed May 16 15:33:49 2018


module rclamp0524p (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \9 );
    inout \1 ;
    inout \10 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \9 ;


    initial
        begin
        end

endmodule
