-- generated by newgenasym Fri Dec 01 11:02:16 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \4pincon\ is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC);
end \4pincon\;
