-- generated by newgenasym Tue Dec 21 14:06:55 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end r;
