-- generated by newgenasym Tue Dec 26 16:39:52 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity spx1117adj is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	OUT_T:     INOUT  STD_LOGIC);
end spx1117adj;
