-- generated by newgenasym Tue Jan 16 16:42:55 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ao3400 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end ao3400;
