// generated by newgenasym  Thu Dec 14 11:50:40 2017


module w25q128 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    input \1 ;
    inout \2 ;
    inout \3 ;
    input \4 ;
    inout \5 ;
    input \6 ;
    inout \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
