-- generated by newgenasym Thu Dec 14 11:50:40 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity w25q128 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end w25q128;
