// generated by newgenasym  Fri Jan 16 17:11:49 2015


module usb_dul (\d+ , \d- , gnd, vbus);
    inout [1:0] \d+ ;
    inout [1:0] \d- ;
    inout [1:0] gnd;
    inout [1:0] vbus;


    initial
        begin
        end

endmodule
