-- generated by newgenasym Fri Jan 16 17:11:49 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity usb_dul is
    port (    
	\d+\:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\d-\:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	GND:       INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VBUS:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0));
end usb_dul;
