-- generated by newgenasym Tue Jan 23 22:46:19 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \eeprom-512k\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end \eeprom-512k\;
