-- generated by newgenasym Thu Aug 07 13:20:43 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \7m_serial\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end \7m_serial\;
